feat: endpoint use `0.0.0.0`
koishijs/koishi-plugin-gocqhttp pull request #20
Opened 2023-05-29 03:54 UTC by uyloal

使用 0.0.0.0 作为 endpoint host，便于在局域网 or 公网中直接连接 gocqhttp。
使用 127.0.0.1 只能被本机访问，如果在 docker 中运行会导致无法便捷的访问

2023-05-29 04:52 UTC, shigma commented
直接暴露不够安全，建议作为配置项。

cc @ilharp 有没有什么建议？

2023-05-29 05:30 UTC, uyloal commented
@shigma  那感觉可以这样？

**setting.vue**
![image](https://github.com/koishijs/koishi-plugin-gocqhttp/assets/37807381/92bb4bcc-69e6-43d0-b8e8-980ad321ce5f)
**src/index.ts**
![image](https://github.com/koishijs/koishi-plugin-gocqhttp/assets/37807381/2d771511-40a2-416e-903c-0a06d48e53c3)
![image](https://github.com/koishijs/koishi-plugin-gocqhttp/assets/37807381/a0c08f17-1aed-4db3-a0af-72125bb81a35)

一开始就这样改的，但测试没跑起来就只改了 127.0.0.1 -> 0.0.0.0。
注入 `setting.vue` 是需要什么特别配置吗，直接从本地路径 install 没办法在 onebot 配置页面看到 gocqhttp 的配置

2023-05-29 14:11 UTC, ilharp commented
> cc @ilharp 有没有什么建议？

我对此功能没有想法。使用 gocqhttp 插件的情况下，不应直接暴露 gocqhttp。这会带来多个方面的问题。

作为配置项将会提高代码的复杂度，如果配置项的逻辑出现错误，将会给用户带来极大的安全风险。因此，如果有人能负责维护和检查此配置项相关的代码，确保它们在每个版本都不会出现问题的话，我觉得可以加配置项；如果没有人维护相关逻辑的话我就倾向于不添加。

2023-05-29 18:20 UTC, shigma commented
配置项直接用 host 吧，默认值就 127.0.0.1。

2023-05-31 04:25 UTC, uyloal commented
> 配置项直接用 host 吧，默认值就 127.0.0.1。

@shigma 根据这个改了一下

2023-05-31 18:33 UTC, shigma requested changes

2023-05-31 18:33 UTC, shigma commented on src/index.ts
> +      const host = this.config.host ?? '127.0.0.1'
`.default()` 会生效，这里不需要 `??`。

2023-05-31 18:33 UTC, shigma commented on src/index.ts
> +    message?: Dict;
请不要修改已有的可用代码，遵循现有的代码风格。

2023-06-01 01:48 UTC, uyloal commented on src/index.ts
> +      const host = this.config.host ?? '127.0.0.1'
已修改 commit: 5420a5a

2023-06-01 01:48 UTC, uyloal commented on src/index.ts
> +    message?: Dict;
已修改 commit: 5420a5a

2023-06-01 18:11 UTC, shigma reviewed
还需要麻烦你处理一下冲突。

2023-06-02 01:11 UTC, uyloal commented
@shigma 已解决冲突

2023-06-02 03:34 UTC, shigma approved these changes

2023-06-02 03:34 UTC, merged

2023-06-02 03:36 UTC, shigma commented
已发布 3.7.3 版本。