feat: make template customizable
koishijs/koishi-plugin-gocqhttp pull request #4
Opened 2022-04-01 01:51 UTC by MaikoTan

Add an option to provide file path of user-customized `template.yml`.

I think this is an advanced feature that most people don't need or don't know how to use, so add in `interface` only, not in `Schema`.

2022-07-11 19:30 UTC, shigma requested changes
a go-cqhttp `config.yml` file usually has hundreds of lines, and it should not be an appropriate practice to directly pass in a string as a template. I recommend only keeping the `template` configuration item as the path notation.

2022-07-12 08:42 UTC, MaikoTan commented
> a go-cqhttp `config.yml` file usually has hundreds of lines, and it should not be an appropriate practice to directly pass in a string as a template. I recommend only keeping the `template` configuration item as the path notation.

I think it is fair to have only the path of the template. In this case, I think just call it template is okay, what do you think?

2022-07-12 08:50 UTC, MaikoTan reviewed
keep template path only

2022-07-12 10:16 UTC, shigma commented on src/index.ts
> +      ? resolve(config.template)
```suggestion
      ? resolve(bot.app.baseDir, config.template)
```

2022-07-12 16:03 UTC, shigma approved these changes

2022-07-12 16:03 UTC, merged